2020-04-27 01:52:12,164 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:54]
2020-04-27 02:09:35,280 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:54]
2020-04-27 02:12:15,528 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:54]
2020-04-27 02:13:51,443 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:54]
2020-04-27 02:15:59,749 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:54]
2020-04-27 02:16:12,039 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:54]
2020-04-27 02:16:36,866 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:54]
2020-04-27 02:16:51,970 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:54]
2020-04-27 02:16:58,975 ERROR: Exception on / [GET] [in /Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/nathanielgertzman/Documents/Python/Flask/microblog/app/routes.py", line 38, in index
    prev_url=prev_url)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/nathanielgertzman/Documents/Python/Flask/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/nathanielgertzman/Documents/Python/Flask/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 12, in block "body"
  File "/Users/nathanielgertzman/Documents/Python/Flask/microblog/app/templates/base.html", line 17, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.index'. Did you mean 'index' instead?
