2020-04-20 01:48:07,485 ERROR: Exception on /reset_password_request [POST] [in /Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_mail.py", line 192, in send
    message.rcpt_options)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/smtplib.py", line 852, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/smtplib.py", line 600, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/smtplib.py", line 440, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/smtplib.py", line 367, in putcmd
    self.send(str)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nathanielgertzman/Documents/Python/Flask/microblog/app/routes.py", line 154, in reset_password_request
    send_password_reset_email(user)
  File "/Users/nathanielgertzman/Documents/Python/Flask/microblog/app/email.py", line 19, in send_password_reset_email
    user = user, token = token))
  File "/Users/nathanielgertzman/Documents/Python/Flask/microblog/app/email.py", line 9, in send_email
    mail.send(msg)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/smtplib.py", line 984, in quit
    res = self.docmd("quit")
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/smtplib.py", line 420, in docmd
    self.putcmd(cmd, args)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/smtplib.py", line 367, in putcmd
    self.send(str)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2020-04-20 02:09:41,863 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:47]
2020-04-20 02:10:16,313 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:47]
2020-04-20 02:14:18,001 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:47]
2020-04-20 02:17:43,005 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:47]
2020-04-20 02:26:25,974 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:47]
2020-04-20 02:26:58,912 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:47]
2020-04-24 14:17:17,992 INFO: Microblog startup [in /Users/nathanielgertzman/Documents/Python/Flask/microblog/app/__init__.py:49]
2020-04-24 14:17:21,482 ERROR: Exception on / [GET] [in /Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/nathanielgertzman/Documents/Python/Flask/microblog/app/routes.py", line 38, in index
    prev_url=prev_url)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/nathanielgertzman/Documents/Python/Flask/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/nathanielgertzman/Documents/Python/Flask/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/Users/nathanielgertzman/Documents/Python/Flask/microblog/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/nathanielgertzman/Documents/Python/Flask/microblog/app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/Users/nathanielgertzman/Documents/Python/Flask/microblog/app/templates/_post.html", line 29, in top-level template code
    {% if post.author.id == g.user.id %}
  File "/Users/nathanielgertzman/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'flask.ctx._AppCtxGlobals object' has no attribute 'user'
